networks:
  webapp:
    driver: overlay
  common:
    driver: overlay

services:
  backend:
    image: keydian-backend:latest
    # open ports in overlay network to communicate each other
    ports:
      - "3014:3014"
    volumes:
      - ./keydian.db:/keydian/keydian.db
    networks:
      - webapp
      - common
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any # no always policy on swarm mode
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        reservations:
          cpus: "0.5"
          memory: 512M
        limits:
          cpus: "1"
          memory: 1024M